In refactoring tests change from xpp3_min to xpp3
jar from http://www.extreme.indiana.edu/dist/java-repository/xpp3/jars/xpp3-1.1.3.4.O.jar
http://www.extreme.indiana.edu/xgws/xsoap/xpp/mxp1/

Fixes this stack trace
org/xmlpull/v1/XmlPullParserFactory

java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParserFactory
at com.thoughtworks.xstream.io.xml.XppDriver.createParser(XppDriver.java:57)
at com.thoughtworks.xstream.io.xml.AbstractXppDriver.createReader(AbstractXppDriver.java:54)
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:913)
at com.thoughtworks.xstream.XStream.fromXML(XStream.java:904)
at org.python.pydev.refactoring.tests.adapter.ModuleAdapterTestCase.runTest(ModuleAdapterTestCase.java:33)